[build-system]
requires      = ["setuptools >= 82.0.1"]
build-backend = "setuptools.build_meta"

[project]
name = "graphicnovelpricescraper"
version = "0.1.3"
dependencies = [
  "playwright>=1.60.0"
]
requires-python = ">=3.10"
authors = [{ name = "Gray Espinoza", email = "grey@grayespinoza.dev" }]
description = "A graphic novel price scraper"
readme = "README.md"
license = "MIT"
keywords = ["scraping", "webscraping", "retail", "prices"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]

[project.urls]
Documentation = "https://github.com/grayespinoza/graphic-novel-price-scraper/blob/main/README.md"
Repository    = "https://github.com/grayespinoza/graphic-novel-price-scraper"
Issues        = "https://github.com/grayespinoza/graphic-novel-price-scraper/issues"

[project.optional-dependencies]
dev = [
  "playwright>=1.60.0",
  "ruff>=0.15.14",
  "codespell>=2.4.2",
  "ty>=0.0.40",
  "tox>=4.55.0",
]
