[tox]
env_list = format, spell, type, lint, test

[testenv:format]
deps =
    ruff
commands =
    ruff format --check

[testenv:spell]
deps =
    codespell
commands =
    codespell

[testenv:type]
deps =
    ty
    pytest
commands =
    ty check

[testenv:lint]
deps =
    ruff
commands =
    ruff check

[testenv:test]
deps =
    pytest
    pytest-asyncio
commands =
    pytest
